---

- hosts: all
  become: true
  tasks: 

  - name: update repo index
    apt:
      update_cache: yes

  - name: install apache2 package
    ansible.builtin.apt:
      name: apache2
      state: latest

  - name: start apache2 service
    ansible.builtin.service:
      name: apache2
      state: started
      enabled: yes

